---

- name: collectd-configure | Setup Collectd service
  template: src=upstart.conf.j2 dest=/etc/init/collectd.conf
  when: collectd_upstart

- name: collectd-configure | Ensure the Collectd is enabled and started
  service: name=collectd state=started enabled=yes

- name: collectd-configure | Setup logs rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/collectd.conf
  when: collectd_logpath and collectd_logrotate
